from list_vpc_sc_supported_services.__main__ import (
    scrape_vpc_service_controls_supported_products,
)
from list_vpc_sc_supported_services.__main__ import remove_mixed_status
from list_vpc_sc_supported_services.__main__ import generate_tf_variable
